version: '3'
services:
  backend:
    image: golang:1.20
    volumes:
      - ./app:/root/app
    working_dir: /root/app
    command: go run ./backend/main.go
    environment:
      - PORT=18080
    ports:
      - 18080:18080
  frontend:
    image: golang:1.20
    volumes:
      - ./app:/root/app
    working_dir: /root/app
    command: go run ./frontend/main.go
    environment:
      - PORT=8080
      - BACKEND_ENDPOINT=http://backend:18080
    ports:
      - 8080:8080
    depends_on:
      - backend
