version: '3'
services:
  backend:
    image: golang:1.20
    volumes:
      - ./app:/root/app
    working_dir: /root/app
    command: go run ./backend/main.go
    environment:
      - PORT=18080
    ports:
      - 18080:18080
  frontend:
    image: golang:1.20
    volumes:
      - ./app:/root/app
    working_dir: /root/app
    command: go run ./frontend/main.go
    environment:
      - PORT=8080
      - BACKEND_ENDPOINT=http://backend:18080
    ports:
      - 8080:8080
    depends_on:
      - backend
  prometheus:
    image: prom/prometheus:v2.37.8
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    depends_on:
      - backend
      - frontend
  grafana:
    image: grafana/grafana:8.2.6
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
